### ISSUE TITLE
net block: investigate using netlink/nl80211 instead of shelling out

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1069]
As long as dependencies don't get too out of hand, this would be a step towards simplifying the block and for us to truly be "pure Rust" (or closer anyway by using C bindings).

- [ ] ip
- [ ] ipv6
- [x] bitrate (https://github.com/greshake/i3status-rust/commit/99062389e24e9026b25874514ace70c60f03634c)
- [x] ssid (completed with #1142)
- [x] frequency (completed with #1142)
- [x] signal strength (completed with #1142)

**Comment by MaxVerevkin** [comment]
The most "popular" crate I found is https://github.com/Eonm/nl80211 and it works fine to get SSID and frequency. Also it is super easy to use (but I didn't figure out how to get signal strength).

Speed can still be calculated form `/sys/class/net/.../statistics/`, there is no problem with it.

https://github.com/jbaublitz/neli can be used to get IPs.

I don't know about bitrate.

**Comment by ammgws** [comment]
https://github.com/doums/baru might be a good reference

**Comment by MaxVerevkin** [comment]
> https://github.com/doums/baru

It displays my signal strength as "100%", but it should be ~50%.

Also found that https://github.com/Eonm/nl80211 in fact has a signal strength in "dBm", only need to convert it.

**Comment by GladOSkar** [comment]
Yeah i honestly have no idea what the `%` numbers are supposed to say anyway, like `%` of what? It's probably some arbitrary threshold

**Comment by MaxVerevkin** [comment]
https://www.intuitibits.com/2016/03/23/dbm-to-percent-conversion/

**Comment by GladOSkar** [comment]
Interesting. As a summary: Yes, there are arbitrary choices (interval, perception curve) but rough common values are:

Logarithmic interval: `[ -100 dBm ; 0 dBm ]`
Perception Curve: Quadratic

**Comment by MaxVerevkin** [comment]
Maybe https://github.com/torvalds/linux/blob/9ff9b0d392ea08090cd1780fb196f36dbb586529/drivers/net/wireless/intel/ipw2x00/ipw2200.c#L4322-L4334 ?

**Comment by MaxVerevkin** [comment]
OK, nl80211 + that formula from some driver gives the same percentage as current block. I'll assume it's correct.

**Comment by MaxVerevkin** [comment]
What I can tell so far: `netlink` is hard.

**Comment by MaxVerevkin** [comment]
Hmm. I've been trying to simply get interfaces name through `netlink`, but it turns out it doesn't give you names. It gives indexes.

OK, how do I get interface name given index? Well, turns out there is a function in `libc` that does exactly that. Weird, if you ask me.

Anyway, that's how it looks
```rust
        unsafe {
            let index = 3; // Get index via netlink
            let mut buff = [0i8; 10];
            libc::if_indextoname(index, &mut buff[0]);
            let buff: [u8; 10] = std::mem::transmute(buff);
            let interface = std::str::from_utf8_unchecked(&buff);
            let interface = interface.trim_matches(char::from(0));
            dbg!(interface);
        };
```

**Comment by MaxVerevkin** [comment]
So, another thing that can be simplified is
https://github.com/greshake/i3status-rust/blob/06925fdacea3ee510bda467844ef39b86896f4a5/src/blocks/net.rs#L80-L99
by using something like
https://github.com/MaxVerevkin/swaystatus/blob/c41249899041254b0f2009d26ff4b527e165f5c1/src/netlink.rs#L23-L32

Does anyone want to do it?

**Comment by ammgws** [comment]
Looks good :) Now that you can get the interface ID from the device name, it shouldn't be much more work to grab it's IP address, right?

> Does anyone want to do it?

To be honest, right now I barely have enough time for basic maintenance tasks so at this point you are pretty much the only active contributor.

**Comment by MaxVerevkin** [comment]
> it shouldn't be much more work to grab it's IP address, right?

Fortunately there is an example in `neli` crate :)

**Comment by farwayer** [comment]
Hey @MaxVerevkin thanks for working on the new net module!
But I just trapped into the issue with new nl80211 code: `failed to get frequency`
Look like for some reason `frequency` is None however device is connected to AP.
Can a net block be more tolerant of such things like `frequency` and `signal` and not throw block_error?

**Comment by MaxVerevkin** [comment]
@farwayer 

> Can a net block be more tolerant of such things like frequency and signal and not throw block_error?

Yeah, sure.

> Look like for some reason frequency is None however device is connected to AP.

Can you please run the following commands to check for sure? (Runs the example from `nl80211` crate that prints all the available info).

```sh
cd /tmp
git clone https://github.com/Eonm/nl80211.git
cd nl80211
cargo run --example show_interfaces
```

**Comment by farwayer** [comment]
```
mac : XX:XX:XX:XX:XX:XX
interface : wlp3s0b1
power : 20 dBm
phy : 1
device : 4294967297

essid : rusty
mac : XX:XX:XX:XX:XX:XX
interface : wlp0s20u2
power : 20 dBm
phy : 0
device : 1
```

**Comment by MaxVerevkin** [comment]
@farwayer And what `iw dev wlp0s20u2 link` outputs?

**Comment by farwayer** [comment]
```
Connected to XX:XX:XX:XX:XX:XX (on wlp0s20u2)
	SSID: rusty
	freq: 2437
	RX: 530230712 bytes (378268 packets)
	TX: 16805071 bytes (105458 packets)
	signal: -31 dBm
	tx bitrate: 144.4 MBit/s

	bss flags:	short-slot-time
	dtim period:	0
	beacon int:	0
```

**Comment by MaxVerevkin** [comment]
That's weird. I don't know why `nl80211` is unable to get the frequency.

**Comment by farwayer** [comment]
The same for ap signal. We can try to contact nl80211 library author https://github.com/Eonm/nl80211
I noticed nl80211 uses outdated [neli](https://github.com/jbaublitz/neli) library. That can be the problem.

**Comment by ammgws** [comment]
@farwayer What ended up happening?

**Comment by MaxVerevkin** [comment]
> I noticed nl80211 uses outdated neli library. That can be the problem.

Hey @farwayer, I ended up [rewriting `nl80211`](https://github.com/MaxVerevkin/nl80211) with latest version of `neli`. It seems to work and it has fewer dependencies. Does it change change anything? (You can run `cargo run --example show_interfaces 2>&1 | grep 'signal: Some' -A2`)

**Comment by MaxVerevkin** [comment]
I wonder if instead of doing https://github.com/greshake/i3status-rust/blob/2e5e0474b9df1e9d3e547bc10550a341e1ea53f4/src/netlink.rs#L77-L103 we can just rely on the `UP` flag of the interface (`ip link` lists flags between `<` and `>` and they're easily obtainable via `netlink`).

**Comment by MaxVerevkin** [comment]
By the way, I think I managed to get `ip`, `ipv6`, `rx_bytes` and `tx_bytes` from `netlink`.

**Comment by MaxVerevkin** [comment]
> OK, how do I get interface name given index? Well, turns out there is a function in libc that does exactly that

Yeah, but I found how to get it without this weird libc function (I wonder if this function actually uses netlink under the hood or not).

**Comment by MaxVerevkin** [comment]
Here's a what I have: https://gist.github.com/MaxVerevkin/6419a79ecb8b85d9e0ec90a48c856d02

This script lists all available interfaces, their state (is it up), IP addresses (v4&v6), upload/download stats, shows which one is the default.

It's better to test this implementation first before integrating it into the net block.
